from __future__ import annotations

import argparse


def add_harness_parser(sub: argparse._SubParsersAction) -> None:
    parser = sub.add_parser("harness", help="scan, scaffold, and validate fuzz harnesses")
    harness_sub = parser.add_subparsers(dest="harness_command", required=True)
    p_h = harness_sub.add_parser("ai-plan", help="emit an AI-ready harness plan for a repo")
    p_h.add_argument("path")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("index", help="write a compile-aware harness candidate index")
    p_h.add_argument("target")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("knowledge", help="write a single-candidate knowledge packet")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", required=True)
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("prompt", help="print a Codex-ready harness authoring prompt for a target")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", help="candidate id or function name from ai-plan/work-order")
    p_h = harness_sub.add_parser("synthesize", help="create and compile an AI harness attempt packet")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", required=True)
    p_h.add_argument("--source", help="existing harness source to compile instead of the generated draft")
    p_h.add_argument("--attempts", type=int, default=5, help="repair attempts to allow in the generated prompt")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("llm-gen", help="write an OSS-Fuzz-Gen style Codex harness generation packet")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", required=True)
    p_h.add_argument("--backend", choices=["codex", "oss-fuzz-gen"], default="codex")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("blockers", help="derive harness blockers from LLVM coverage")
    p_h.add_argument("target")
    p_h.add_argument("--run")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("suspicious-points", help="rank uncovered parser/decoder points for the next harness")
    p_h.add_argument("target")
    p_h.add_argument("--run")
    p_h.add_argument("--limit", type=int, default=12)
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("qa", help="check harnesses against the four production fuzzing principles")
    p_h.add_argument("target")
    p_h.add_argument("--candidate")
    p_h.add_argument("--run")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("iterate", help="write a coverage-guided harness iteration packet")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", help="candidate id or function name")
    p_h.add_argument("--run")
    p_h = harness_sub.add_parser("fuzztest-plan", help="write a FuzzTest property-harness plan")
    p_h.add_argument("target")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("fuzztest-generate", help="write a non-applied FuzzTest template for one candidate")
    p_h.add_argument("target")
    p_h.add_argument("--candidate", required=True)
    p_h.add_argument("--property", default="never_crashes", choices=["never_crashes", "roundtrip", "api_invariant"])
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("work-order", help="write a full AI harness work-order packet")
    p_h.add_argument("target")
    p_h.add_argument("--limit", type=int, default=8)
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("review", help="review harness code for fuzz-loop safety")
    p_h.add_argument("target")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("score", help="score harness readiness from review, builds, seeds, and coverage")
    p_h.add_argument("target")
    p_h.add_argument("--run")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("scan", help="scan a repo for likely harness entrypoints")
    p_h.add_argument("path")
    p_h.add_argument("--json", action="store_true")
    p_h = harness_sub.add_parser("scaffold", help="create a reviewed harness template")
    p_h.add_argument("target")
    p_h.add_argument("--type", choices=["libfuzzer", "file", "stdin"], required=True)
    p_h.add_argument("--harness-name", default="candidate")
    p_h.add_argument("--function")
    p_h = harness_sub.add_parser("validate", help="validate harness manifest shape")
    p_h.add_argument("target")
    p_h.add_argument("--build", action="store_true")
